window.CONTENU = {
"meta": {
  "titre": "Livrets de positionnement",
  "sous_titre": "Arabe standard moderne (Fusha) — Années 1 à 5",
  "etablissement": "Association de la Fraternité d'Elne",
  "conception": "M. KADDOURI / Y. NAJIH",
  "annee_scolaire": "2026-2027",
  "conditions": {
    "1": {"lettres": 20, "nombres": 7, "plage": "1 à 10"},
    "2": {"lettres": 28, "nombres": 21, "plage": "0 à 20"}
  }
},
"parties": [
  {"id": "co", "nom": "Compréhension orale", "court": "Écoute"},
  {"id": "ce", "nom": "Compréhension écrite", "court": "Lecture"},
  {"id": "pe", "nom": "Production écrite", "court": "Écriture"},
  {"id": "po", "nom": "Production orale", "court": "Oral"}
],
"consignes": {
  "c-accueil": "Bonjour ! Regarde bien l'écran et écoute. Tu écris tes réponses sur ta feuille. Si tu ne sais pas, laisse la case vide : ce n'est pas grave.",
  "c-fin": "C'est terminé. Bravo ! Pose ton crayon.",
  "c-lettre-entendue": "Écoute le nom de la lettre. Entoure cette lettre sur ta feuille.",
  "c-son-syllabe": "Écoute le son. Entoure ce que tu entends.",
  "c-dictee-lettre": "Écoute le nom de la lettre. Écris cette lettre dans la case.",
  "c-recopier-mot": "Recopie le mot dans la case, de droite à gauche.",
  "c-ajouter-voyelle": "Écoute. Ajoute la bonne voyelle sur la lettre.",
  "c-lire-image": "Lis le mot. Entoure le numéro de la bonne image.",
  "c-lire-couleur": "Lis le mot. Entoure le numéro de la bonne couleur.",
  "c-ecouter-image": "Écoute. Entoure le numéro de la bonne image.",
  "c-ecouter-nombre": "Écoute le nombre. Écris-le en chiffres dans la case.",
  "c-ecrire-image": "Regarde l'image. Écris le mot en arabe.",
  "c-accord": "Complète la phrase avec le mot entre parenthèses, bien accordé.",
  "c-recopier-phrase": "Recopie la phrase, de droite à gauche.",
  "c-lire-phrase-image": "Lis la phrase. Entoure le numéro de la bonne image.",
  "c-conjuguer-present": "Écris le verbe au présent pour compléter la phrase.",
  "c-pronom": "Complète le mot avec la bonne fin.",
  "c-pluriel": "Écris le pluriel du mot.",
  "c-lettre-surlignee": "Regarde la lettre soulignée en couleur. Entoure cette lettre écrite toute seule.",
  "c-lire-texte": "Lis le texte en silence. Puis réponds à la question.",
  "c-solaire-lunaire": "Écoute le mot. Lettre solaire ou lettre lunaire ? Entoure le soleil ou la lune.",
  "c-passe": "Écris le verbe au passé pour compléter la phrase.",
  "c-futur": "Écris le verbe au futur proche pour compléter la phrase.",
  "c-ordre-mots": "Remets les mots dans l'ordre : d'abord le verbe, puis le sujet, puis le complément. Écris la phrase.",
  "c-passe-futur": "Écoute la phrase. C'est déjà passé, ou ça va arriver ? Entoure la bonne flèche.",
  "c-ecouter-recit": "Écoute l'histoire. Puis réponds à la question.",
  "c-racine": "Trouve les trois lettres de la racine commune à ces mots. Écris-les dans les cases.",
  "c-traduire": "Écris en arabe l'expression en français.",
  "c-intrus": "Écoute les trois mots. Entoure le numéro du mot qui n'a pas la même racine.",
  "c-premiere-lettre": "Écoute le mot. Entoure la lettre par laquelle il commence.",
  "c-ecouter-couleur": "Écoute. Entoure le numéro de la bonne couleur.",
  "c-ecouter-visage": "Écoute. Entoure le visage qui correspond.",
  "c-comptine": "Écoute la comptine. De quoi parle-t-elle ? Entoure le bon dessin.",
  "c-syllabe-image": "Regarde l'image. Entoure la syllabe par laquelle commence le mot.",
  "c-ecouter-mot": "Écoute le mot. Entoure le mot que tu entends.",
  "c-ecouter-dialogue": "Écoute le dialogue. Puis réponds à la question.",
  "c-shadda": "Lis les mots. Entoure le mot qui a une shadda.",
  "c-completer-fr": "Lis le français. Complète la phrase en arabe.",
  "c-ecouter-mot-phrase": "Écoute la phrase. Entoure le mot comme tu l'entends dans la phrase.",
  "c-ecouter-moment": "Écoute la phrase. Quand est-ce ? Entoure le bon dessin.",
  "c-ecouter-reponse": "Écoute. Puis entoure la bonne réponse.",
  "c-ecouter-ami": "Ton ami te dit cette phrase. Écoute. Entoure ce que tu lui réponds.",
  "c-ecouter-scheme": "Écoute le mot. Est-ce une personne, un lieu ou une chose faite ? Entoure le bon dessin."
},
"entretien": {
  "seuil": 6,
  "items": [
    {"id": "P1", "dit": "اِجْلِسْ !", "tr": "ijlis !", "attendu": "l'élève s'assoit", "source": "A1 · Consignes de classe"},
    {"id": "P2", "dit": "قِفْ !", "tr": "qif !", "attendu": "l'élève se lève", "source": "A1 · Consignes de classe"},
    {"id": "P3", "dit": "اِسْتَمِعْ !", "tr": "istami' !", "attendu": "main à l'oreille", "source": "A1 · Consignes de classe"},
    {"id": "P4", "dit": "أَيْنَ الكِتَابُ ؟", "tr": "ayna l-kitābu ?", "attendu": "montre le livre (image 2)", "source": "A1 · Mots outils ; Objets de la classe"},
    {"id": "P5", "dit": "السَّلَامُ عَلَيْكُمْ", "tr": "as-salāmu 'alaykum", "attendu": "وَعَلَيْكُمُ السَّلَامُ", "source": "A1 · Salutations"},
    {"id": "P6", "dit": "مَا اسْمُكَ ؟ / مَا اسْمُكِ ؟", "tr": "mā smuka / mā smuki ?", "attendu": "اِسْمِي …", "source": "A1 · Expressions conversationnelles"},
    {"id": "P7", "dit": "كَمْ عُمْرُكَ ؟ / كَمْ عُمْرُكِ ؟", "tr": "kam 'umruka / 'umruki ?", "attendu": "عُمْرِي … (سَنَوَاتٍ)", "source": "A1 · Expressions conversationnelles"},
    {"id": "P8", "dit": "كَيْفَ حَالُكَ ؟ / كَيْفَ حَالُكِ ؟", "tr": "kayfa ḥāluka / ḥāluki ?", "attendu": "بِخَيْرٍ، الحَمْدُ لِلَّهِ", "source": "A1 · Expressions conversationnelles"}
  ],
  "p4_images": ["crayon", "livre", "sac"],
  "prononciation": [
    {"mot": "حَلِيبٌ", "son": "ح"}, {"mot": "عَصِيرٌ", "son": "ع"},
    {"mot": "صَلَاةٌ", "son": "ص"}, {"mot": "قِطٌّ", "son": "ق"}
  ],
  "reperage": ["بَ", "سِ", "قَلَمٌ"],
  "alphabet": [
    {"lettre": "ر", "nom": "رَاء"}, {"lettre": "ك", "nom": "كَاف"}, {"lettre": "ب", "nom": "بَاء"},
    {"lettre": "ع", "nom": "عَيْن"}, {"lettre": "س", "nom": "سِين"}, {"lettre": "ذ", "nom": "ذَال"},
    {"lettre": "ي", "nom": "يَاء"}, {"lettre": "ح", "nom": "حَاء"}, {"lettre": "ط", "nom": "طَاء"},
    {"lettre": "ل", "nom": "لَام"}, {"lettre": "ث", "nom": "ثَاء"}, {"lettre": "ف", "nom": "فَاء"},
    {"lettre": "ج", "nom": "جِيم"}, {"lettre": "ش", "nom": "شِين"}, {"lettre": "ا", "nom": "أَلِف"},
    {"lettre": "ق", "nom": "قَاف"}, {"lettre": "ض", "nom": "ضَاد"}, {"lettre": "ن", "nom": "نُون"},
    {"lettre": "خ", "nom": "خَاء"}, {"lettre": "و", "nom": "وَاو"}, {"lettre": "ص", "nom": "صَاد"},
    {"lettre": "ظ", "nom": "ظَاء"}, {"lettre": "م", "nom": "مِيم"}, {"lettre": "د", "nom": "دَال"},
    {"lettre": "غ", "nom": "غَيْن"}, {"lettre": "ت", "nom": "تَاء"}, {"lettre": "ز", "nom": "زَاي"},
    {"lettre": "ه", "nom": "هَاء"}
  ],
  "nombres": {
    "un_a_dix": [
      {"n": 7, "nom": "سَبْعَة"}, {"n": 2, "nom": "اِثْنَان"}, {"n": 10, "nom": "عَشَرَة"}, {"n": 4, "nom": "أَرْبَعَة"},
      {"n": 1, "nom": "وَاحِد"}, {"n": 6, "nom": "سِتَّة"}, {"n": 9, "nom": "تِسْعَة"}, {"n": 3, "nom": "ثَلَاثَة"},
      {"n": 8, "nom": "ثَمَانِيَة"}, {"n": 5, "nom": "خَمْسَة"}
    ],
    "zero_et_onze_a_vingt": [
      {"n": 15, "nom": "خَمْسَةَ عَشَرَ"}, {"n": 0, "nom": "صِفْرٌ"}, {"n": 19, "nom": "تِسْعَةَ عَشَرَ"},
      {"n": 12, "nom": "اِثْنَا عَشَرَ"}, {"n": 20, "nom": "عِشْرُون"}, {"n": 14, "nom": "أَرْبَعَةَ عَشَرَ"},
      {"n": 17, "nom": "سَبْعَةَ عَشَرَ"}, {"n": 11, "nom": "أَحَدَ عَشَرَ"}, {"n": 18, "nom": "ثَمَانِيَةَ عَشَرَ"},
      {"n": 13, "nom": "ثَلَاثَةَ عَشَرَ"}, {"n": 16, "nom": "سِتَّةَ عَشَرَ"}
    ]
  }
},
"livrets": [
{
  "numero": 1, "annee": 1, "couleur": "#2d7d8a", "bareme": {"total": 24, "reussi": 18, "orientation": 12}, "textes": {},
  "items": [
    {"id": "1-01", "partie": "co", "type": "choix", "consigne": "c-lettre-entendue", "son": "ar-1-01", "options": ["ح", "خ", "ج"], "reponse": 3, "source": "A1 · Compréhension orale : reconnaître les 28 lettres à l'écoute"},
    {"id": "1-02", "partie": "co", "type": "choix", "consigne": "c-lettre-entendue", "son": "ar-1-02", "options": ["ت", "ب", "ث"], "reponse": 1, "source": "A1 · Compréhension orale ; lettres à points"},
    {"id": "1-03", "partie": "co", "type": "choix", "consigne": "c-premiere-lettre", "son": "ar-1-haqiba", "options": ["ه", "ح", "خ"], "reponse": 2, "source": "A1 · Phonétique : ح / هـ ; Objets de la classe"},
    {"id": "1-04", "partie": "co", "type": "choix", "consigne": "c-premiere-lettre", "son": "ar-1-ayn", "options": ["أ", "غ", "ع"], "reponse": 3, "source": "A1 · Phonétique : ع / أ ; Corps humain"},
    {"id": "1-05", "partie": "co", "type": "choix", "consigne": "c-premiere-lettre", "son": "ar-1-sabboura", "options": ["س", "ص", "ث"], "reponse": 1, "source": "A1 · Phonétique : ص / س ; Objets de la classe"},
    {"id": "1-06", "partie": "co", "type": "choix", "consigne": "c-premiere-lettre", "son": "ar-1-daftar", "options": ["ض", "د", "ذ"], "reponse": 2, "source": "A1 · Phonétique : ض / د ; Objets de la classe"},
    {"id": "1-07", "partie": "co", "type": "choix", "consigne": "c-premiere-lettre", "son": "ar-1-tawila", "options": ["ت", "ظ", "ط"], "reponse": 3, "source": "A1 · Phonétique : ط / ت ; Objets de la classe"},
    {"id": "1-08", "partie": "co", "type": "choix", "consigne": "c-premiere-lettre", "son": "ar-1-koursi", "options": ["ك", "ق", "ف"], "reponse": 1, "source": "A1 · Phonétique : ق / ك ; Objets de la classe"},
    {"id": "1-09", "partie": "co", "type": "choix", "consigne": "c-son-syllabe", "son": "ar-1-04", "options": ["بَ", "بِ", "بُ"], "reponse": 3, "source": "A1 · Voyelles courtes"},
    {"id": "1-10", "partie": "co", "type": "ecrire", "consigne": "c-ajouter-voyelle", "son": "ar-1-08", "enonce": "بـ", "reponse": "بِ", "tolerance": "Kasra sous la lettre.", "source": "A1 · Voyelles courtes"},
    {"id": "1-11", "partie": "co", "type": "choix-images", "consigne": "c-ecouter-image", "son": "ar-1-13", "options": ["poule", "lapin", "chien"], "reponse": 3, "source": "A1 · Animaux domestiques"},
    {"id": "1-12", "partie": "co", "type": "choix-images", "consigne": "c-ecouter-image", "son": "ar-1-14", "options": ["banane", "pomme", "orange"], "reponse": 2, "source": "A1 · Nourriture"},
    {"id": "1-13", "partie": "co", "type": "choix-couleurs", "consigne": "c-ecouter-couleur", "son": "ar-1-azraq", "options": ["#f2c511", "#1f5fd6", "#e87fb0"], "libelles": ["jaune", "bleu", "rose"], "reponse": 2, "source": "A1 · Couleurs"},
    {"id": "1-14", "partie": "co", "type": "choix-images", "consigne": "c-ecouter-visage", "son": "ar-1-hazin", "options": ["garcon-content", "garcon-triste", "garcon-colere"], "reponse": 2, "source": "A1 · Émotions"},
    {"id": "1-15", "partie": "co", "type": "chiffres", "consigne": "c-ecouter-nombre", "son": "ar-1-15", "reponse": "7", "tolerance": "7 ou ٧ accepté.", "source": "A1 · Nombres 1-10"},
    {"id": "1-16", "partie": "co", "type": "choix-icones", "consigne": "c-comptine", "son": "ar-1-comptine", "options": ["couleurs", "animaux", "nombres"], "reponse": 3, "source": "A1 · Compréhension orale : identifier le thème d'une comptine ; Nombres 1-10"},
    {"id": "1-17", "partie": "ce", "type": "choix-images", "consigne": "c-lire-image", "enonce": "سَمَكٌ", "options": ["oiseau", "poisson", "chat"], "reponse": 2, "source": "A1 · Animaux domestiques"},
    {"id": "1-18", "partie": "ce", "type": "choix-images", "consigne": "c-lire-image", "enonce": "قَلَمٌ", "options": ["crayon", "sac", "livre"], "reponse": 1, "source": "A1 · Objets de la classe"},
    {"id": "1-19", "partie": "ce", "type": "choix-images", "consigne": "c-lire-image", "enonce": "يَدٌ", "options": ["pied", "oeil", "main"], "reponse": 3, "source": "A1 · Corps humain"},
    {"id": "1-20", "partie": "ce", "type": "choix-couleurs", "consigne": "c-lire-couleur", "enonce": "أَحْمَرُ", "options": ["#1f5fd6", "#d62828", "#2a9d3a"], "libelles": ["bleu", "rouge", "vert"], "reponse": 2, "source": "A1 · Couleurs"},
    {"id": "1-21", "partie": "ce", "type": "choix", "consigne": "c-syllabe-image", "image": "poule", "options": ["دَ", "دِ", "دُ"], "reponse": 1, "source": "A1 · Lecture : syllabes consonne + voyelle courte ; Animaux domestiques (دَجَاجَةٌ)"},
    {"id": "1-22", "partie": "pe", "type": "ecrire", "consigne": "c-dictee-lettre", "son": "ar-1-05", "reponse": "د", "tolerance": "Lettre isolée reconnaissable.", "source": "A1 · Écriture : les 12 lettres sans point"},
    {"id": "1-23", "partie": "pe", "type": "ecrire", "consigne": "c-dictee-lettre", "son": "ar-1-06", "reponse": "م", "tolerance": "Lettre isolée reconnaissable.", "source": "A1 · Écriture : les 12 lettres sans point"},
    {"id": "1-24", "partie": "pe", "type": "ecrire", "consigne": "c-recopier-mot", "enonce": "رَأْسٌ", "reponse": "رَأْسٌ", "tolerance": "Bonnes lettres, bien liées, de droite à gauche ; voyelles non exigées.", "source": "A1 · Écriture (copie) ; Corps humain"}
  ]
},
{
  "numero": 2, "annee": 2, "couleur": "#a8731a", "bareme": {"total": 34, "reussi": 26, "orientation": 17},
  "textes": {
    "M": "هَذِهِ أُخْتِي مَرْيَمُ. هِيَ طَوِيلَةٌ وَجَمِيلَةٌ. شَعْرُهَا أَسْوَدُ. تَلْبَسُ فُسْتَانًا أَزْرَقَ. عِنْدَهَا قِطٌّ صَغِيرٌ. تُحِبُّ العِنَبَ، وَلَا تُحِبُّ الحَلِيبَ."
  },
  "items": [
    {"id": "2-01", "partie": "co", "type": "choix", "consigne": "c-ecouter-mot", "son": "ar-2-jamil", "options": ["جَمَلٌ", "جَمِيلٌ", "جَمَالٌ"], "reponse": 2, "source": "A2 · Voyelles longues : distinguer voyelle courte et longue ; Adjectifs (جَمِيل)"},
    {"id": "2-02", "partie": "co", "type": "choix", "consigne": "c-premiere-lettre", "son": "ar-2-dhahr", "options": ["ذ", "ز", "ظ"], "reponse": 3, "source": "A2 · Points de vigilance : ذ / ز / ظ ; Corps (ظَهْر)"},
    {"id": "2-03", "partie": "co", "type": "chiffres", "consigne": "c-ecouter-nombre", "son": "ar-2-13", "reponse": "15", "tolerance": "15 ou ١٥ accepté.", "source": "A2 · Nombres 11-20"},
    {"id": "2-04", "partie": "co", "type": "choix-images", "consigne": "c-ecouter-image", "son": "ar-2-15", "options": ["chat-sur-table", "chat-sous-table", "chat-cote-table"], "reponse": 2, "source": "A2 · Prépositions spatiales"},
    {"id": "2-05", "partie": "co", "type": "choix-images", "consigne": "c-ecouter-recit", "son": "ar-2-recit", "question": "Qu'est-ce que Youssef boit ?", "options": ["lait", "the", "jus-orange"], "reponse": 1, "source": "A2 · CO : suivre une histoire simple (routine) ; Nourriture"},
    {"id": "2-06", "partie": "co", "type": "choix-images", "consigne": "c-ecouter-recit", "son": "ar-2-recit", "question": "Quel temps fait-il ?", "options": ["neige", "soleil-brulant", "pluie"], "reponse": 1, "source": "A2 · Météo (بَارِد)"},
    {"id": "2-07", "partie": "co", "type": "choix-images", "consigne": "c-ecouter-recit", "son": "ar-2-recit", "question": "Que porte Youssef ?", "options": ["manteau", "robe", "chapeau"], "reponse": 1, "source": "A2 · Vêtements (مِعْطَف)"},
    {"id": "2-08", "partie": "co", "type": "choix-images", "consigne": "c-ecouter-recit", "son": "ar-2-recit", "question": "Où va Youssef ensuite ?", "options": ["stade", "ecole", "marche"], "reponse": 2, "source": "A2 · CO : identifier les actions ; École"},
    {"id": "2-09", "partie": "co", "type": "choix-images", "consigne": "c-ecouter-dialogue", "sons": ["ar-2-dialogue-1", "ar-2-dialogue-2", "ar-2-dialogue-3", "ar-2-dialogue-4", "ar-2-dialogue-5", "ar-2-dialogue-6"], "question": "Où va Omar le vendredi ?", "options": ["mosquee", "ecole", "marche"], "reponse": 1, "source": "A2 · Dialogue 6 : les jours de la semaine"},
    {"id": "2-10", "partie": "co", "type": "choix-images", "consigne": "c-ecouter-dialogue", "sons": ["ar-2-dialogue-1", "ar-2-dialogue-2", "ar-2-dialogue-3", "ar-2-dialogue-4", "ar-2-dialogue-5", "ar-2-dialogue-6"], "question": "Que fait Omar le samedi ?", "options": ["garcon-dort", "enfants-jouent", "garcon-ecrit"], "reponse": 2, "source": "A2 · Dialogue 6 ; Verbes d'action"},
    {"id": "2-11", "partie": "co", "type": "choix-fr", "consigne": "c-ecouter-dialogue", "sons": ["ar-2-dialogue-1", "ar-2-dialogue-2", "ar-2-dialogue-3", "ar-2-dialogue-4", "ar-2-dialogue-5", "ar-2-dialogue-6"], "question": "Omar aime-t-il les carottes ?", "options": ["oui", "non"], "reponse": 2, "source": "A2 · Dialogue 4 : goûts ; La négation (لَا أُحِبُّ)"},
    {"id": "2-12", "partie": "co", "type": "choix-images", "consigne": "c-ecouter-dialogue", "sons": ["ar-2-dialogue-1", "ar-2-dialogue-2", "ar-2-dialogue-3", "ar-2-dialogue-4", "ar-2-dialogue-5", "ar-2-dialogue-6"], "question": "Quel fruit Omar aime-t-il ?", "options": ["banane", "fraise", "pomme"], "reponse": 3, "source": "A2 · Dialogue 4 ; Fruits"},
    {"id": "2-13", "partie": "ce", "type": "choix-fr", "consigne": "c-lire-texte", "texte": "M", "question": "Qui est Mariam pour l'enfant qui parle ?", "options": ["sa sœur", "sa mère", "son amie"], "reponse": 1, "source": "A2 · CE : lire un texte court vocalisé ; Famille"},
    {"id": "2-14", "partie": "ce", "type": "choix-images", "consigne": "c-lire-texte", "texte": "M", "question": "Que porte Mariam ?", "options": ["fille-chemise-rouge", "fille-chemise-bleue", "fille-robe-bleue"], "reponse": 3, "source": "A2 · Décrire une personne ; Vêtements"},
    {"id": "2-15", "partie": "ce", "type": "choix-images", "consigne": "c-lire-texte", "texte": "M", "question": "Qu'est-ce que Mariam n'aime pas ?", "options": ["lait", "raisin", "chat"], "reponse": 1, "source": "A2 · Goûts ; La négation"},
    {"id": "2-16", "partie": "ce", "type": "choix-images", "consigne": "c-lire-phrase-image", "enonce": "عِنْدَهَا قَمِيصٌ أَحْمَرُ", "options": ["garcon-chemise-rouge", "fille-chemise-bleue", "fille-chemise-rouge"], "reponse": 3, "source": "A2 · Possession (عِنْدَ) ; Vêtements"},
    {"id": "2-17", "partie": "ce", "type": "choix", "consigne": "c-shadda", "options": ["بَيْتٌ", "حَمَّامٌ", "مَطْبَخٌ"], "reponse": 2, "source": "A2 · Signes diacritiques : shadda ; Maison"},
    {"id": "2-18", "partie": "pe", "type": "ecrire", "consigne": "c-ecrire-image", "image": "maison", "reponse": "بَيْتٌ", "tolerance": "Consonnes correctes (بيت) ; voyelles non exigées.", "source": "A2 · Production écrite : écrire des mots sans modèle ; Maison"},
    {"id": "2-19", "partie": "pe", "type": "ecrire", "consigne": "c-ecrire-image", "image": "soleil", "reponse": "شَمْسٌ", "tolerance": "Consonnes correctes (شمس) ; voyelles non exigées.", "source": "A2 · Production écrite ; Météo"},
    {"id": "2-20", "partie": "pe", "type": "ecrire", "consigne": "c-accord", "enonce": "البِنْتُ ……… .", "indice": "(كَبِيرٌ)", "reponse": "كَبِيرَةٌ", "tolerance": "Terminaison féminine ة exigée ; voyelles non exigées.", "source": "A2 · Genre et accord"},
    {"id": "2-21", "partie": "pe", "type": "ecrire", "consigne": "c-recopier-phrase", "enonce": "أَنَا سَعِيدٌ", "reponse": "أَنَا سَعِيدٌ", "tolerance": "Bonnes lettres, bien liées, de droite à gauche ; voyelles non exigées.", "source": "A2 · Production écrite : copier des phrases courtes ; Phrase nominale"},
    {"id": "2-22", "partie": "pe", "type": "ecrire", "consigne": "c-completer-fr", "fr": "« Elle a un petit chat. »", "enonce": "……… قِطٌّ صَغِيرٌ.", "reponse": "عِنْدَهَا", "tolerance": "عندها attendu ; voyelles non exigées.", "source": "A2 · Exprimer la possession (عِنْدَ)"},
    {"id": "2-23", "partie": "pe", "type": "ecrire", "consigne": "c-completer-fr", "fr": "« Ce n'est pas un livre. »", "enonce": "……… هَذَا كِتَابًا.", "reponse": "لَيْسَ", "tolerance": "ليس attendu ; voyelles non exigées.", "source": "A2 · La négation simple (exemple du référentiel)"},
    {"id": "2-24", "partie": "pe", "type": "ecrire", "consigne": "c-completer-fr", "fr": "« Où est le livre ? »", "enonce": "……… الكِتَابُ؟", "reponse": "أَيْنَ", "tolerance": "أين attendu (أ ou ا) ; voyelles non exigées.", "source": "A2 · Les interrogatifs (exemple du référentiel)"}
  ],
  "oral": [
    {"question": "مَنْ هَذِهِ؟ مَاذَا تَلْبَسُ؟", "image": "fille-chemise-rouge", "geste": "Montrez l'image de la fille en chemise rouge.", "vise": "Décrire une personne et ses vêtements", "attendu": "هَذِهِ بِنْتٌ. تَلْبَسُ قَمِيصًا أَحْمَرَ."},
    {"question": "مَا هَذَا؟ … مَا هَذِهِ؟", "geste": "Montrez un livre, puis une table.", "vise": "Nommer des objets avec هَذَا / هَذِهِ", "attendu": "هَذَا كِتَابٌ. هَذِهِ طَاوِلَةٌ."},
    {"question": "أَيْنَ القَلَمُ؟", "geste": "Posez un crayon sur, sous ou dans un objet de la classe.", "vise": "Situer un objet", "attendu": "القَلَمُ عَلَى الطَّاوِلَةِ."},
    {"question": "مَاذَا تُحِبُّ؟ هَلْ تُحِبُّ الجَزَرَ؟ / مَاذَا تُحِبِّينَ؟ هَلْ تُحِبِّينَ الجَزَرَ؟", "vise": "Exprimer ses goûts, avec la négation", "attendu": "أُحِبُّ… / لَا، لَا أُحِبُّ الجَزَرَ."},
    {"question": "كَيْفَ الطَّقْسُ اليَوْمَ؟", "vise": "Parler du temps qu'il fait", "attendu": "الطَّقْسُ جَمِيلٌ / حَارٌّ / بَارِدٌ."}
  ]
},
{
  "numero": 3, "annee": 3, "couleur": "#b94a32", "bareme": {"total": 34, "reussi": 26, "orientation": 17},
  "textes": {
    "A": "سَارَةُ تِلْمِيذَةٌ مِنْ فَرَنْسَا. هِيَ ذَكِيَّةٌ وَنَشِيطَةٌ. عِنْدَهَا دَرَّاجَةٌ جَدِيدَةٌ، لَكِنْ كُلَّ صَبَاحٍ، تَذْهَبُ إِلَى المَدْرَسَةِ بِالحَافِلَةِ. مُعَلِّمَتُهَا لَطِيفَةٌ جِدًّا. فِي الفُسْحَةِ، تَلْعَبُ فِي المَلْعَبِ مَعَ صَدِيقَتِهَا. ظُهْرًا، تَأْكُلُ فِي المَقْصَفِ. بَعْدَ المَدْرَسَةِ، تَشْرَبُ الحَلِيبَ وَتَقْرَأُ كِتَابًا. مَسَاءً، تَكْتُبُ وَاجِبَهَا ثُمَّ تَنَامُ. تُحِبُّ سَارَةُ يَوْمَ السَّبْتِ لِأَنَّهَا تَلْعَبُ مَعَ أَخِيهَا فِي الحَدِيقَةِ."
  },
  "items": [
    {"id": "3-01", "partie": "co", "type": "choix-icones", "consigne": "c-solaire-lunaire", "son": "ar-3-13", "options": ["soleil", "lune"], "reponse": 1, "source": "A3 · Lettres solaires et lunaires"},
    {"id": "3-02", "partie": "co", "type": "choix-icones", "consigne": "c-solaire-lunaire", "son": "ar-3-14", "options": ["soleil", "lune"], "reponse": 2, "source": "A3 · Lettres solaires et lunaires"},
    {"id": "3-03", "partie": "co", "type": "choix", "consigne": "c-ecouter-mot-phrase", "son": "ar-3-tanwin", "options": ["كِتَابٌ", "كِتَابًا", "كِتَابٍ"], "reponse": 2, "source": "A3 · Le tanwīn : trois formes (exemple du référentiel)"},
    {"id": "3-04", "partie": "co", "type": "choix-images", "consigne": "c-ecouter-image", "son": "ar-3-15", "options": ["garcon-ecrit", "fille-lit", "fille-ecrit"], "reponse": 3, "source": "A3 · Conjugaison du présent"},
    {"id": "3-05", "partie": "co", "type": "choix-images", "consigne": "c-ecouter-image", "son": "ar-3-16", "options": ["enfants-jouent", "garcon-joue-seul", "fille-ecrit"], "reponse": 1, "source": "A3 · Conjugaison du présent"},
    {"id": "3-06", "partie": "co", "type": "choix-images", "consigne": "c-ecouter-image", "son": "ar-3-mouallimoun", "options": ["enseignante", "enseignants", "enseignantes"], "reponse": 2, "source": "A3 · Le pluriel (مُعَلِّمُونَ / مُعَلِّمَاتٌ) ; Métiers"},
    {"id": "3-07", "partie": "co", "type": "choix-icones", "consigne": "c-ecouter-moment", "son": "ar-3-masaan", "options": ["matin", "midi", "soir"], "reponse": 3, "source": "A3 · Le temps (صَبَاحًا، ظُهْرًا، مَسَاءً)"},
    {"id": "3-08", "partie": "co", "type": "choix-images", "consigne": "c-ecouter-image", "son": "ar-3-sayyara", "options": ["bus", "voiture", "velo"], "reponse": 2, "source": "A3 · Prépositions إِلَى et بِـ ; Transports"},
    {"id": "3-09", "partie": "co", "type": "choix-fr", "consigne": "c-ecouter-recit", "son": "ar-3-recit", "question": "Combien de personnes y a-t-il dans la famille de Youssef ?", "options": ["3", "4", "5"], "reponse": 3, "source": "A3 · CO : extraire les informations ; Dialogue 5 (famille)"},
    {"id": "3-10", "partie": "co", "type": "choix-images", "consigne": "c-ecouter-recit", "son": "ar-3-recit", "question": "Quel est le métier du père ?", "options": ["ingenieur", "medecin", "cuisinier"], "reponse": 1, "source": "A3 · Métiers"},
    {"id": "3-11", "partie": "co", "type": "choix-icones", "consigne": "c-ecouter-recit", "son": "ar-3-recit", "question": "D'où vient la grand-mère ?", "options": ["drapeau-algerie", "drapeau-maroc", "drapeau-france"], "reponse": 2, "source": "A3 · Nationalités (مَغْرِبِيٌّ)"},
    {"id": "3-12", "partie": "co", "type": "choix-fr", "consigne": "c-ecouter-recit", "son": "ar-3-recit", "question": "Pourquoi Youssef aime-t-il sa grand-mère ?", "options": ["elle est riche", "elle est drôle", "elle est gentille"], "reponse": 3, "source": "A3 · Adjectifs ; Connecteurs (لِأَنَّ)"},
    {"id": "3-13", "partie": "co", "type": "choix-images", "consigne": "c-ecouter-dialogue", "sons": ["ar-3-dialogue-1", "ar-3-dialogue-2", "ar-3-dialogue-3", "ar-3-dialogue-4", "ar-3-dialogue-5", "ar-3-dialogue-6", "ar-3-dialogue-7", "ar-3-dialogue-8"], "question": "Où est Sara ?", "options": ["medecin-cabinet", "ecole", "marche"], "reponse": 1, "source": "A3 · Dialogue 2 : chez le médecin"},
    {"id": "3-14", "partie": "co", "type": "choix-images", "consigne": "c-ecouter-dialogue", "sons": ["ar-3-dialogue-1", "ar-3-dialogue-2", "ar-3-dialogue-3", "ar-3-dialogue-4", "ar-3-dialogue-5", "ar-3-dialogue-6", "ar-3-dialogue-7", "ar-3-dialogue-8"], "question": "Qu'est-ce qui fait mal à Sara ?", "options": ["fille-mal-ventre", "fille-mal-pied", "fille-mal-tete"], "reponse": 3, "source": "A3 · Dialogue 2 ; Corps humain"},
    {"id": "3-15", "partie": "co", "type": "choix-fr", "consigne": "c-ecouter-dialogue", "sons": ["ar-3-dialogue-1", "ar-3-dialogue-2", "ar-3-dialogue-3", "ar-3-dialogue-4", "ar-3-dialogue-5", "ar-3-dialogue-6", "ar-3-dialogue-7", "ar-3-dialogue-8"], "question": "Depuis quand est-elle malade ?", "options": ["depuis hier", "depuis une semaine", "depuis ce matin"], "reponse": 1, "source": "A3 · Le temps (أَمْسِ) ; Dialogue 2"},
    {"id": "3-16", "partie": "co", "type": "choix-images", "consigne": "c-ecouter-dialogue", "sons": ["ar-3-dialogue-1", "ar-3-dialogue-2", "ar-3-dialogue-3", "ar-3-dialogue-4", "ar-3-dialogue-5", "ar-3-dialogue-6", "ar-3-dialogue-7", "ar-3-dialogue-8"], "question": "Que doit faire Sara ?", "options": ["fille-boit-eau", "fille-bonbons", "enfants-jouent"], "reponse": 1, "source": "A3 · CO : comprendre les consignes ; Dialogue 2"},
    {"id": "3-17", "partie": "ce", "type": "lettre-surlignee", "consigne": "c-lettre-surlignee", "surligne": {"avant": "", "segment": "عَ", "apres": "يْنٌ"}, "options": ["غ", "ع", "ح"], "reponse": 2, "source": "A3 · Les 28 lettres dans toutes les positions"},
    {"id": "3-18", "partie": "ce", "type": "lettre-surlignee", "consigne": "c-lettre-surlignee", "surligne": {"avant": "دَفْ", "segment": "تَ", "apres": "رٌ"}, "options": ["ب", "ن", "ت"], "reponse": 3, "source": "A3 · Les 28 lettres dans toutes les positions"},
    {"id": "3-19", "partie": "ce", "type": "choix-images", "consigne": "c-lire-texte", "texte": "A", "question": "Comment Sara va-t-elle à l'école ?", "options": ["voiture", "bus", "velo"], "reponse": 2, "source": "A3 · Compréhension écrite ; Transports"},
    {"id": "3-20", "partie": "ce", "type": "choix-fr", "consigne": "c-lire-texte", "texte": "A", "question": "Après l'école, Sara…", "options": ["boit du lait et lit un livre", "joue dans la cour", "prend le bus"], "reponse": 1, "source": "A3 · Compréhension écrite"},
    {"id": "3-21", "partie": "ce", "type": "choix-fr", "consigne": "c-lire-texte", "texte": "A", "question": "Dans le texte, que veut dire « المَقْصَفِ » ?", "options": ["la classe", "la cour", "la cantine"], "reponse": 3, "source": "A3 · CE : déduire le sens d'un mot du contexte ; Vocabulaire scolaire"},
    {"id": "3-22", "partie": "pe", "type": "ecrire", "consigne": "c-conjuguer-present", "enonce": "أَنَا ……… إِلَى المَدْرَسَةِ.", "indice": "(يَذْهَبُ)", "reponse": "أَذْهَبُ", "tolerance": "Préfixe أ exigé ; voyelles non exigées ; une faute sur une lettre du radical tolérée.", "source": "A3 · Conjugaison du présent"},
    {"id": "3-23", "partie": "pe", "type": "ecrire", "consigne": "c-pronom", "fr": "son livre (à elle)", "enonce": "كِتَابُـ……", "image": "fille-livre", "reponse": "كِتَابُهَا", "tolerance": "Fin ها exigée ; voyelles non exigées.", "source": "A3 · Pronoms suffixes"},
    {"id": "3-24", "partie": "pe", "type": "ecrire", "consigne": "c-pluriel", "enonce": "كِتَابٌ", "reponse": "كُتُبٌ", "tolerance": "كتب attendu ; voyelles non exigées.", "source": "A3 · Le pluriel (exemple du référentiel)"}
  ],
  "oral": [
    {"question": "مِنْ أَيْنَ أَنْتَ؟ / مِنْ أَيْنَ أَنْتِ؟", "vise": "Dire d'où l'on vient (مِنْ, nationalité)", "attendu": "أَنَا مِنْ فَرَنْسَا. / أَنَا فَرَنْسِيٌّ (فَرَنْسِيَّةٌ)."},
    {"question": "مَنْ فِي عَائِلَتِكَ؟ / مَنْ فِي عَائِلَتِكِ؟", "vise": "Présenter sa famille (pronom suffixe ـي)", "attendu": "أَبِي وَأُمِّي وَأَخِي…"},
    {"question": "مَاذَا تَفْعَلُ فِي الصَّبَاحِ؟ / مَاذَا تَفْعَلِينَ فِي الصَّبَاحِ؟", "vise": "Deux actions au présent, liées par ثُمَّ", "attendu": "آكُلُ الخُبْزَ، ثُمَّ أَذْهَبُ إِلَى المَدْرَسَةِ."},
    {"question": "هَلْ تُحِبُّ المَدْرَسَةَ؟ لِمَاذَا؟ / هَلْ تُحِبِّينَ المَدْرَسَةَ؟ لِمَاذَا؟", "vise": "Donner son avis avec لِأَنَّ", "attendu": "نَعَمْ، أُحِبُّ المَدْرَسَةَ لِأَنَّ المُعَلِّمَةَ لَطِيفَةٌ."},
    {"question": "مَاذَا تَفْعَلُ البِنْتُ؟", "image": "fille-lit", "geste": "Montrez l'image de la fille qui lit.", "vise": "Décrire une image au présent", "attendu": "هِيَ تَقْرَأُ كِتَابًا."}
  ]
},
{
  "numero": 4, "annee": 4, "couleur": "#4a55a2", "bareme": {"total": 34, "reussi": 26, "orientation": 17},
  "textes": {
    "B": "عُمَرُ تِلْمِيذٌ مِنْ فَرَنْسَا. فِي الصَّيْفِ المَاضِي، سَافَرَ مَعَ عَائِلَتِهِ إِلَى المَغْرِبِ. كَانَ عُمَرُ مُتَحَمِّسًا جِدًّا. فِي الرِّبَاطِ، زَارُوا صَوْمَعَةَ حَسَّانَ. كَانَ الطَّقْسُ حَارًّا جِدًّا، فَسَبَحَ عُمَرُ فِي البَحْرِ مَعَ أَخِيهِ. ثُمَّ رَكِبُوا القِطَارَ إِلَى مَرَّاكُشَ. هُنَاكَ، مَشَى عُمَرُ فِي السُّوقِ القَدِيمِ، وَاشْتَرَى تَمْرًا لِجَدَّتِهِ وَهَدِيَّةً لِصَدِيقِهِ. أَكَلُوا الطَّاجِينَ وَالكُسْكُسَ، وَكَانَ الأَكْلُ لَذِيذًا. فِي المَسَاءِ، جَلَسُوا فِي مَقْهًى وَشَرِبُوا الشَّايَ. مَا نَسِيَ عُمَرُ هَذِهِ الرِّحْلَةَ أَبَدًا! فِي العُطْلَةِ، سَيَزُورُ جَدَّتَهُ مَعَ أُمِّهِ، إِنْ شَاءَ اللَّهُ."
  },
  "items": [
    {"id": "4-01", "partie": "co", "type": "choix-icones", "consigne": "c-passe-futur", "son": "ar-4-13", "options": ["passe", "futur"], "reponse": 1, "source": "A4 · Exemples contextualisés"},
    {"id": "4-02", "partie": "co", "type": "choix-icones", "consigne": "c-passe-futur", "son": "ar-4-14", "options": ["passe", "futur"], "reponse": 2, "source": "A4 · Le futur proche"},
    {"id": "4-03", "partie": "co", "type": "choix-fr", "consigne": "c-ecouter-reponse", "son": "ar-4-dhahabou", "question": "Qui est allé au marché ?", "image": "marche", "options": ["eux", "lui", "nous"], "reponse": 1, "source": "A4 · Le passé (هُمْ كَتَبُوا)"},
    {"id": "4-04", "partie": "co", "type": "choix-fr", "consigne": "c-ecouter-reponse", "son": "ar-4-ma-dhahabtou", "question": "Qu'as-tu entendu ?", "image": "ecole", "options": ["Je suis allé à l'école.", "Je ne suis pas allé à l'école.", "Je n'irai pas à l'école."], "reponse": 2, "source": "A4 · La négation (مَا + passé, لَنْ + futur)"},
    {"id": "4-05", "partie": "co", "type": "choix-images", "consigne": "c-ecouter-visage", "son": "ar-4-khaif", "options": ["garcon-fier", "garcon-content", "garcon-effraye"], "reponse": 3, "source": "A4 · Sentiments (خَائِف)"},
    {"id": "4-06", "partie": "co", "type": "choix-images", "consigne": "c-ecouter-image", "son": "ar-4-soudaa", "options": ["fille-mal-tete", "fille-mal-ventre", "fille-mal-pied"], "reponse": 1, "source": "A4 · Santé (صُدَاع)"},
    {"id": "4-07", "partie": "co", "type": "choix", "consigne": "c-ecouter-ami", "son": "ar-4-najahtou", "options": ["مَعَ السَّلَامَةِ", "لَا بَأْسَ", "مُبَارَكٌ"], "reponse": 3, "source": "A4 · Expressions courantes (مُبَارَكٌ)"},
    {"id": "4-08", "partie": "co", "type": "choix-images", "consigne": "c-ecouter-recit", "son": "ar-4-recit", "question": "Où Khaled est-il allé ?", "options": ["ecole", "stade", "marche"], "reponse": 2, "source": "A4 · Compréhension orale ; Ville"},
    {"id": "4-09", "partie": "co", "type": "choix-images", "consigne": "c-ecouter-recit", "son": "ar-4-recit", "question": "Qu'a-t-il bu ?", "options": ["lait", "the", "jus-orange"], "reponse": 3, "source": "A4 · Compréhension orale"},
    {"id": "4-10", "partie": "co", "type": "choix-images", "consigne": "c-ecouter-recit", "son": "ar-4-recit", "question": "Comment se sentait Khaled au début ?", "options": ["garcon-colere", "garcon-inquiet", "garcon-triste"], "reponse": 2, "source": "A4 · Sentiments (قَلِق)"},
    {"id": "4-11", "partie": "co", "type": "choix-images", "consigne": "c-ecouter-recit", "son": "ar-4-recit", "question": "Qu'est-ce que son équipe a gagné ?", "options": ["medaille", "ballon", "coupe"], "reponse": 3, "source": "A4 · Sports (كَأْس)"},
    {"id": "4-12", "partie": "co", "type": "choix-images", "consigne": "c-ecouter-dialogue", "sons": ["ar-4-dialogue-1", "ar-4-dialogue-2", "ar-4-dialogue-3", "ar-4-dialogue-4", "ar-4-dialogue-5", "ar-4-dialogue-6", "ar-4-dialogue-7", "ar-4-dialogue-8"], "question": "Où Leila veut-elle aller ?", "options": ["musee", "pharmacie", "stade"], "reponse": 1, "source": "A4 · Dialogue 2 : dans une rue d'Alger ; Ville"},
    {"id": "4-13", "partie": "co", "type": "choix-icones", "consigne": "c-ecouter-dialogue", "sons": ["ar-4-dialogue-1", "ar-4-dialogue-2", "ar-4-dialogue-3", "ar-4-dialogue-4", "ar-4-dialogue-5", "ar-4-dialogue-6", "ar-4-dialogue-7", "ar-4-dialogue-8"], "question": "Quel chemin doit-elle prendre ?", "options": ["itineraire-droit-droite", "itineraire-droit-gauche", "itineraire-droite-droit"], "reponse": 1, "source": "A4 · Dialogue 2 : indiquer un chemin (مُسْتَقِيمًا، يَمِينًا)"},
    {"id": "4-14", "partie": "co", "type": "choix-fr", "consigne": "c-ecouter-dialogue", "sons": ["ar-4-dialogue-1", "ar-4-dialogue-2", "ar-4-dialogue-3", "ar-4-dialogue-4", "ar-4-dialogue-5", "ar-4-dialogue-6", "ar-4-dialogue-7", "ar-4-dialogue-8"], "question": "Le musée est-il loin ?", "image": "rue-alger", "options": ["oui, à une heure en bus", "non, à dix minutes à pied", "oui, il faut prendre le train"], "reponse": 2, "source": "A4 · Dialogue 2 (قَرِيب، بَعِيد)"},
    {"id": "4-15", "partie": "co", "type": "choix-images", "consigne": "c-ecouter-dialogue", "sons": ["ar-4-dialogue-1", "ar-4-dialogue-2", "ar-4-dialogue-3", "ar-4-dialogue-4", "ar-4-dialogue-5", "ar-4-dialogue-6", "ar-4-dialogue-7", "ar-4-dialogue-8"], "question": "Qu'y a-t-il juste à côté du musée ?", "options": ["ecole", "pharmacie", "cafe"], "reponse": 3, "source": "A4 · Ville (مَقْهًى) ; Prépositions (بِجَانِبِ)"},
    {"id": "4-16", "partie": "ce", "type": "choix-fr", "consigne": "c-lire-texte", "texte": "B", "question": "Quand Omar a-t-il voyagé ?", "options": ["l'hiver dernier", "l'été dernier", "l'été prochain"], "reponse": 2, "source": "A4 · Compréhension écrite"},
    {"id": "4-17", "partie": "ce", "type": "choix-fr", "consigne": "c-lire-texte", "texte": "B", "question": "Quelles villes la famille a-t-elle visitées ?", "options": ["Rabat et Marrakech", "Alger et Oran", "Tunis et Le Caire"], "reponse": 1, "source": "A4 · Compréhension écrite"},
    {"id": "4-18", "partie": "ce", "type": "choix-images", "consigne": "c-lire-texte", "texte": "B", "question": "Qu'a-t-il acheté pour sa grand-mère ?", "options": ["sac", "orange", "dattes"], "reponse": 3, "source": "A4 · Compréhension écrite"},
    {"id": "4-19", "partie": "ce", "type": "vrai-faux", "consigne": "c-lire-texte", "texte": "B", "question": "Vrai ou faux : « Il faisait froid. »", "options": ["vrai", "faux"], "reponse": 2, "source": "A4 · Compréhension écrite"},
    {"id": "4-20", "partie": "ce", "type": "choix-images", "consigne": "c-lire-texte", "texte": "B", "question": "Que fera Omar pendant les vacances ?", "options": ["garcon-grand-mere", "garcon-football", "paris"], "reponse": 1, "source": "A4 · Le futur (سَـ) ; Compréhension écrite"},
    {"id": "4-21", "partie": "pe", "type": "ecrire", "consigne": "c-passe", "enonce": "أَنَا ……… الدَّرْسَ.", "indice": "(كَتَبَ)", "reponse": "كَتَبْتُ", "tolerance": "Fin تُ exigée ; voyelles non exigées ; une faute sur une lettre du radical tolérée.", "source": "A4 · Le passé"},
    {"id": "4-22", "partie": "pe", "type": "ecrire", "consigne": "c-passe", "enonce": "هِيَ ……… الكِتَابَ.", "indice": "(قَرَأَ)", "reponse": "قَرَأَتْ", "tolerance": "Fin تْ exigée ; voyelles non exigées.", "source": "A4 · Le passé"},
    {"id": "4-23", "partie": "pe", "type": "ecrire", "consigne": "c-futur", "enonce": "هِيَ ……… إِلَى المَدْرَسَةِ.", "indice": "(تَذْهَبُ)", "reponse": "سَتَذْهَبُ", "tolerance": "Préfixe سَـ exigé devant تذهب ; voyelles non exigées.", "source": "A4 · Le futur proche"},
    {"id": "4-24", "partie": "pe", "type": "ecrire", "consigne": "c-ordre-mots", "mots": ["التُّفَّاحَةَ", "أَكَلَ", "الوَلَدُ"], "image": "garcon-mange-pomme", "reponse": "أَكَلَ الوَلَدُ التُّفَّاحَةَ", "tolerance": "Ordre verbe-sujet-objet exact ; voyelles non exigées.", "source": "A4 · Phrase verbale (VSO)"}
  ],
  "oral": [
    {"question": "مَاذَا فَعَلْتَ أَمْسِ؟ / مَاذَا فَعَلْتِ أَمْسِ؟", "vise": "Raconter au passé (1re personne)", "attendu": "ذَهَبْتُ إِلَى… ثُمَّ لَعِبْتُ…"},
    {"question": "مَاذَا سَتَفْعَلُ فِي العُطْلَةِ؟ / مَاذَا سَتَفْعَلِينَ فِي العُطْلَةِ؟", "vise": "Parler d'un projet au futur (سَـ / سَوْفَ)", "attendu": "سَأُسَافِرُ… / سَأَلْعَبُ…"},
    {"question": "مَا هِوَايَتُكَ؟ هَلْ تُمَارِسُ رِيَاضَةً؟ / مَا هِوَايَتُكِ؟ هَلْ تُمَارِسِينَ رِيَاضَةً؟", "vise": "Parler de ses loisirs et de son sport", "attendu": "أُحِبُّ الرَّسْمَ. أَلْعَبُ كُرَةَ القَدَمِ."},
    {"question": "كَيْفَ تَشْعُرُ اليَوْمَ؟ لِمَاذَا؟ / كَيْفَ تَشْعُرِينَ اليَوْمَ؟ لِمَاذَا؟", "vise": "Exprimer un sentiment et le justifier", "attendu": "أَنَا فَرِحٌ (فَرِحَةٌ) لِأَنَّ…"},
    {"question": "هَلْ ذَهَبْتَ إِلَى السِّينِمَا أَمْسِ؟ / هَلْ ذَهَبْتِ إِلَى السِّينِمَا أَمْسِ؟", "vise": "Répondre à la forme négative au passé (مَا)", "attendu": "لَا، مَا ذَهَبْتُ إِلَى السِّينِمَا."}
  ]
},
{
  "numero": 5, "annee": 5, "couleur": "#2e7d4f", "bareme": {"total": 34, "reussi": 26, "orientation": 17},
  "textes": {
    "D": "فِي العُطْلَةِ، سَافَرَتْ لِينَا مَعَ وَالِدِهَا وَوَالِدَتِهَا إِلَى الجَزَائِرِ. كَانَ الجَوُّ جَمِيلًا، وَالشَّمْسُ مُشْرِقَةً. أَوَّلًا، مَشَوْا فِي القَصَبَةِ، وَزَارُوا الجَامِعَ الكَبِيرَ. ثُمَّ سَافَرُوا بِالقِطَارِ إِلَى قُسَنْطِينَةَ، مَدِينَةِ الجُسُورِ. هُنَاكَ، تَسْكُنُ جَدَّتُهَا فِي بَيْتٍ قَدِيمٍ. غُرْفَةُ لِينَا فِي الطَّابِقِ الثَّانِي، بِجَانِبِ غُرْفَةِ خَالَتِهَا. عَبَرَتْ لِينَا جِسْرَ سِيدِي مْسِيدٍ مَعَ ابْنِ عَمِّهَا، وَكَانَ العُبُورُ مُخِيفًا قَلِيلًا! بَعْدَ ذَلِكَ، زَارُوا مَتْحَفَ المَدِينَةِ. فِي المَسَاءِ، أَكَلُوا الكُسْكُسَ فِي بَيْتِ جَدِّهَا، وَطَبَخَتْ خَالَتُهَا الشَّخْشُوخَةَ أَيْضًا. كَانَ الأَكْلُ لَذِيذًا جِدًّا. فِي آخِرِ يَوْمٍ، رَكِبَتِ العَائِلَةُ الحَافِلَةَ إِلَى وَهْرَانَ لِزِيَارَةِ صَدِيقٍ. أَخِيرًا، اِشْتَرَتْ لِينَا تَمْرًا لِصَدِيقَتِهَا، لِأَنَّهَا تُحِبُّ التَّمْرَ كَثِيرًا. كَانَتْ رِحْلَةً رَائِعَةً، وَتُرِيدُ لِينَا أَنْ تَعُودَ قَرِيبًا، إِنْ شَاءَ اللَّهُ."
  },
  "items": [
    {"id": "5-01", "partie": "co", "type": "intrus", "consigne": "c-intrus", "sons": ["ar-5-13-1", "ar-5-13-2", "ar-5-13-3"], "options": ["1", "2", "3"], "reponse": 3, "source": "A5 · Compréhension orale : identifier les mots-racines à l'oral"},
    {"id": "5-02", "partie": "co", "type": "intrus", "consigne": "c-intrus", "sons": ["ar-5-14-1", "ar-5-14-2", "ar-5-14-3"], "options": ["1", "2", "3"], "reponse": 2, "source": "A5 · Compréhension orale : identifier les mots-racines à l'oral"},
    {"id": "5-03", "partie": "co", "type": "choix-icones", "consigne": "c-ecouter-scheme", "son": "ar-5-malaab", "options": ["personne", "lieu", "chose"], "reponse": 2, "source": "A5 · Schème du lieu (مَفْعَل)"},
    {"id": "5-04", "partie": "co", "type": "choix-icones", "consigne": "c-ecouter-scheme", "son": "ar-5-rakib", "options": ["lieu", "chose", "personne"], "reponse": 3, "source": "A5 · Schème de l'agent (فَاعِل)"},
    {"id": "5-05", "partie": "co", "type": "choix-fr", "consigne": "c-ecouter-reponse", "son": "ar-5-zurna", "question": "Qui a visité le musée ?", "image": "musee", "options": ["nous", "moi", "eux"], "reponse": 1, "source": "A5 · Passé des verbes comme زَارَ (زُرْنَا)"},
    {"id": "5-06", "partie": "co", "type": "choix-fr", "consigne": "c-ecouter-reponse", "son": "ar-5-baytuhum", "question": "De quelle maison parle-t-on ?", "image": "maison", "options": ["leur maison", "sa maison", "votre maison"], "reponse": 1, "source": "A5 · Pronoms suffixes (ـهُمْ)"},
    {"id": "5-07", "partie": "co", "type": "choix-fr", "consigne": "c-ecouter-reponse", "son": "ar-5-khali", "question": "Qui est-ce ?", "image": "famille", "options": ["le frère de mon père", "le frère de ma mère", "mon grand-père"], "reponse": 2, "source": "A5 · Famille (خَال / عَمّ)"},
    {"id": "5-08", "partie": "co", "type": "choix-images", "consigne": "c-ecouter-recit", "son": "ar-5-recit", "question": "Qu'a fait Yassine en premier ?", "options": ["garcon-nage", "garcon-mange-poisson", "garcon-dort"], "reponse": 1, "source": "A5 · Compréhension orale ; connecteurs"},
    {"id": "5-09", "partie": "co", "type": "choix-images", "consigne": "c-ecouter-recit", "son": "ar-5-recit", "question": "Où a-t-il dormi ?", "options": ["maison", "hotel", "grand-pere"], "reponse": 2, "source": "A5 · Compréhension orale"},
    {"id": "5-10", "partie": "co", "type": "choix-images", "consigne": "c-ecouter-recit", "son": "ar-5-recit", "question": "Comment la famille est-elle venue à Oran ?", "options": ["avion", "train", "bateau"], "reponse": 3, "source": "A5 · Transports (سَفِينَة) ; racine ر-ك-ب"},
    {"id": "5-11", "partie": "co", "type": "choix-images", "consigne": "c-ecouter-recit", "son": "ar-5-recit", "question": "Qui a préparé le poisson ?", "options": ["cuisinier", "maman", "garcon-content"], "reponse": 1, "source": "A5 · Racine ط-ب-خ (طَبَخَ، الطَّبَّاخ)"},
    {"id": "5-12", "partie": "co", "type": "choix-fr", "consigne": "c-ecouter-dialogue", "sons": ["ar-5-dialogue-1", "ar-5-dialogue-2", "ar-5-dialogue-3", "ar-5-dialogue-4", "ar-5-dialogue-5", "ar-5-dialogue-6", "ar-5-dialogue-7", "ar-5-dialogue-8"], "question": "Où Amina veut-elle aller ?", "image": "guichet-gare", "options": ["à Alger", "à Constantine", "à Oran"], "reponse": 1, "source": "A5 · Dialogue 4 : à la gare d'Oran"},
    {"id": "5-13", "partie": "co", "type": "choix-fr", "consigne": "c-ecouter-dialogue", "sons": ["ar-5-dialogue-1", "ar-5-dialogue-2", "ar-5-dialogue-3", "ar-5-dialogue-4", "ar-5-dialogue-5", "ar-5-dialogue-6", "ar-5-dialogue-7", "ar-5-dialogue-8"], "question": "Quand veut-elle partir ?", "image": "guichet-gare", "options": ["ce soir", "demain matin", "la semaine prochaine"], "reponse": 2, "source": "A5 · Dialogue 4 ; Voyage"},
    {"id": "5-14", "partie": "co", "type": "choix-icones", "consigne": "c-ecouter-dialogue", "sons": ["ar-5-dialogue-1", "ar-5-dialogue-2", "ar-5-dialogue-3", "ar-5-dialogue-4", "ar-5-dialogue-5", "ar-5-dialogue-6", "ar-5-dialogue-7", "ar-5-dialogue-8"], "question": "À quelle heure part le train ?", "image": "guichet-gare", "options": ["horloge-9h30", "horloge-10h", "horloge-8h"], "reponse": 3, "source": "A5 · Dialogue 4 (مَوْعِدُ الِانْطِلَاقِ)"},
    {"id": "5-15", "partie": "co", "type": "choix-fr", "consigne": "c-ecouter-dialogue", "sons": ["ar-5-dialogue-1", "ar-5-dialogue-2", "ar-5-dialogue-3", "ar-5-dialogue-4", "ar-5-dialogue-5", "ar-5-dialogue-6", "ar-5-dialogue-7", "ar-5-dialogue-8"], "question": "Combien de temps dure le trajet ?", "image": "guichet-gare", "options": ["une heure", "deux heures", "quatre heures"], "reponse": 3, "source": "A5 · Dialogue 4 ; Transports"},
    {"id": "5-16", "partie": "ce", "type": "choix-images", "consigne": "c-lire-texte", "texte": "D", "question": "Qu'a fait la famille en premier ?", "options": ["famille-couscous", "casbah", "train"], "reponse": 2, "source": "A5 · Compréhension écrite ; connecteurs"},
    {"id": "5-17", "partie": "ce", "type": "choix-images", "consigne": "c-lire-texte", "texte": "D", "question": "Comment sont-ils allés à Constantine ?", "options": ["train", "avion", "bus"], "reponse": 1, "source": "A5 · Compréhension écrite"},
    {"id": "5-18", "partie": "ce", "type": "ecrire", "consigne": "c-lire-texte", "texte": "D", "question": "Écris un mot du texte qui vient de la racine و - ل - د.", "reponse": "وَالِدِهَا", "accepte": ["وَالِدِهَا", "وَالِدَتِهَا"], "tolerance": "Toute forme listée, avec ou sans voyelles.", "source": "A5 · Compréhension écrite : identifier les racines"},
    {"id": "5-19", "partie": "ce", "type": "ecrire", "consigne": "c-lire-texte", "texte": "D", "question": "Recopie une annexion de deux noms du texte.", "reponse": "مَدِينَةِ الجُسُورِ", "accepte": ["مَدِينَةِ الجُسُورِ", "بَيْتِ جَدِّهَا", "غُرْفَةُ لِينَا", "غُرْفَةِ خَالَتِهَا", "ابْنِ عَمِّهَا", "مَتْحَفَ المَدِينَةِ", "آخِرِ يَوْمٍ"], "tolerance": "Toute annexion de la liste, avec ou sans voyelles.", "source": "A5 · Compréhension écrite : l'annexion dans les textes"},
    {"id": "5-20", "partie": "ce", "type": "choix-fr", "consigne": "c-lire-texte", "texte": "D", "question": "Qui a cuisiné la chakhchoukha ?", "options": ["sa grand-mère", "sa tante", "sa mère"], "reponse": 2, "source": "A5 · Famille (خَالَة) ; racine ط-ب-خ"},
    {"id": "5-21", "partie": "pe", "type": "racine", "consigne": "c-racine", "enonce": "رَاكِبٌ ، مَرْكَبٌ ، رُكُوبٌ", "reponse": "ر - ك - ب", "tolerance": "Les 3 bonnes lettres dans l'ordre ; tirets facultatifs.", "source": "A5 · Système des racines"},
    {"id": "5-22", "partie": "pe", "type": "ecrire", "consigne": "c-traduire", "fr": "« la porte de l'école »", "reponse": "بَابُ المَدْرَسَةِ", "tolerance": "باب المدرسة accepté sans voyelles ; 0 si article sur le premier nom.", "source": "A5 · L'annexion (الإِضَافَةُ)"},
    {"id": "5-23", "partie": "pe", "type": "ecrire", "consigne": "c-pronom", "fr": "votre maison", "enonce": "بَيْتُـ……", "reponse": "بَيْتُكُمْ", "tolerance": "Fin كم exigée ; voyelles non exigées.", "source": "A5 · Pronoms suffixes (ـكُمْ)"},
    {"id": "5-24", "partie": "pe", "type": "ecrire", "consigne": "c-passe", "enonce": "أَنَا ……… قُسَنْطِينَةَ.", "indice": "(زَارَ)", "reponse": "زُرْتُ", "tolerance": "زرت attendu (sans alif) ; voyelles non exigées.", "source": "A5 · Passé des verbes comme زَارَ (زُرْتُ)"}
  ],
  "oral": [
    {"question": "أَيْنَ تَسْكُنُ؟ صِفْ بَيْتَكَ. / أَيْنَ تَسْكُنِينَ؟ صِفِي بَيْتَكِ.", "vise": "Décrire son logement (سَكَنَ, annexion, pronoms suffixes)", "attendu": "أَسْكُنُ فِي… غُرْفَتِي… غُرْفَةُ أَخِي…"},
    {"question": "حَدِّثْنِي عَنْ رِحْلَةٍ: أَيْنَ ذَهَبْتَ؟ / حَدِّثِينِي عَنْ رِحْلَةٍ: أَيْنَ ذَهَبْتِ؟", "vise": "Raconter un voyage au passé avec des connecteurs", "attendu": "أَوَّلًا رَكِبْتُ… ثُمَّ زُرْتُ… أَخِيرًا…"},
    {"question": "مَنْ فِي عَائِلَتِكَ الكَبِيرَةِ؟ / مَنْ فِي عَائِلَتِكِ الكَبِيرَةِ؟", "vise": "Présenter la famille élargie (عَمّ، خَال، اِبْنُ عَمِّي)", "attendu": "عِنْدِي عَمٌّ وَخَالَةٌ… اِبْنُ عَمِّي…"},
    {"question": "كَتَبَ: اُذْكُرْ كَلِمَتَيْنِ مِنْ نَفْسِ الجَذْرِ. / اُذْكُرِي كَلِمَتَيْنِ مِنْ نَفْسِ الجَذْرِ.", "geste": "Dites d'abord le verbe كَتَبَ.", "vise": "Donner deux mots de la même racine (ك-ت-ب)", "attendu": "كِتَابٌ، كَاتِبٌ، مَكْتَبَةٌ، مَكْتُوبٌ…"},
    {"question": "مَا طَبَقُكَ المُفَضَّلُ؟ مَنْ يَطْبُخُهُ؟ / مَا طَبَقُكِ المُفَضَّلُ؟ مَنْ يَطْبُخُهُ؟", "vise": "Parler de cuisine (ط-ب-خ, pronoms suffixes)", "attendu": "طَبَقِي المُفَضَّلُ الكُسْكُسُ. أُمِّي تَطْبُخُهُ."}
  ]
}
],
"sons": {
  "ar-1-01": "جِيم", "ar-1-02": "تَاء", "ar-1-04": "بُ",
  "ar-1-05": "دَال", "ar-1-06": "مِيم", "ar-1-08": "بِ",
  "ar-1-13": "كَلْبٌ", "ar-1-14": "تُفَّاحَةٌ", "ar-1-15": "سَبْعَة",
  "ar-2-13": "خَمْسَةَ عَشَر",
  "ar-2-15": "القِطُّ تَحْتَ الطَّاوِلَةِ",
  "ar-3-13": "الطَّاوِلَةُ", "ar-3-14": "القَلَمُ", "ar-3-15": "هِيَ تَكْتُبُ", "ar-3-16": "نَحْنُ نَلْعَبُ",
  "ar-4-13": "أَكَلْنَا الطَّعَامَ", "ar-4-14": "سَنَذْهَبُ إِلَى المَدْرَسَةِ",
  "ar-5-13-1": "طَبَّاخٌ", "ar-5-13-2": "مَطْبَخٌ", "ar-5-13-3": "زَائِرٌ",
  "ar-5-14-1": "عُبُورٌ", "ar-5-14-2": "مَسْكَنٌ", "ar-5-14-3": "مَعْبَرٌ",
  "ar-1-haqiba": "حَقِيبَةٌ", "ar-1-ayn": "عَيْنٌ", "ar-1-sabboura": "سَبُّورَةٌ", "ar-1-daftar": "دَفْتَرٌ",
  "ar-1-tawila": "طَاوِلَةٌ", "ar-1-koursi": "كُرْسِيٌّ", "ar-1-azraq": "أَزْرَقُ", "ar-1-hazin": "حَزِينٌ",
  "ar-1-comptine": "وَاحِدٌ، اِثْنَانِ، ثَلَاثَةٌ، أَرْبَعَةٌ، خَمْسَةٌ",
  "ar-2-jamil": "جَمِيلٌ", "ar-2-dhahr": "ظَهْرٌ",
  "ar-2-recit": "فِي الصَّبَاحِ، يَأْكُلُ يُوسُفُ الخُبْزَ وَالجُبْنَ، وَيَشْرَبُ الحَلِيبَ. الجَوُّ بَارِدٌ. يَلْبَسُ يُوسُفُ مِعْطَفًا. ثُمَّ يَمْشِي مَعَ أُخْتِهِ إِلَى المَدْرَسَةِ.",
  "ar-2-dialogue-1": "أَيْنَ تَذْهَبُ يَوْمَ الجُمُعَةِ يَا عُمَرُ؟",
  "ar-2-dialogue-2": "أَذْهَبُ إِلَى المَسْجِدِ مَعَ أَبِي.",
  "ar-2-dialogue-3": "وَيَوْمَ السَّبْتِ؟",
  "ar-2-dialogue-4": "أَلْعَبُ مَعَ أَصْدِقَائِي.",
  "ar-2-dialogue-5": "هَلْ تُحِبُّ الجَزَرَ؟",
  "ar-2-dialogue-6": "لَا، لَا أُحِبُّ الجَزَرَ. أُحِبُّ التُّفَّاحَ!",
  "ar-3-tanwin": "أَقْرَأُ كِتَابًا جَدِيدًا", "ar-3-mouallimoun": "المُعَلِّمُونَ",
  "ar-3-masaan": "أَلْعَبُ فِي الحَدِيقَةِ مَسَاءً", "ar-3-sayyara": "أَذْهَبُ إِلَى السُّوقِ بِالسَّيَّارَةِ",
  "ar-3-recit": "فِي عَائِلَةِ يُوسُفَ خَمْسَةُ أَشْخَاصٍ: الأَبُ، وَالأُمُّ، وَالأَخُ الكَبِيرُ، وَالأُخْتُ الصَّغِيرَةُ، وَيُوسُفُ. الأَبُ مُهَنْدِسٌ، وَالأُمُّ مُعَلِّمَةٌ. الأَخُ الكَبِيرُ طَبَّاخٌ فِي مَطْعَمٍ. الجَدَّةُ مَغْرِبِيَّةٌ، وَهِيَ تَطْبُخُ الكُسْكُسَ يَوْمَ الجُمُعَةِ. يُحِبُّ يُوسُفُ جَدَّتَهُ كَثِيرًا لِأَنَّهَا لَطِيفَةٌ.",
  "ar-3-dialogue-1": "أَهْلًا يَا سَارَةُ. كَيْفَ حَالُكِ اليَوْمَ؟",
  "ar-3-dialogue-2": "أَنَا مَرِيضَةٌ. رَأْسِي يُؤْلِمُنِي.",
  "ar-3-dialogue-3": "مُنْذُ مَتَى؟",
  "ar-3-dialogue-4": "مُنْذُ أَمْسِ. وَعِنْدِي حَرَارَةٌ أَيْضًا.",
  "ar-3-dialogue-5": "اِفْتَحِي فَمَكِ مِنْ فَضْلِكِ.",
  "ar-3-dialogue-6": "هَلْ أَنَا مَرِيضَةٌ جِدًّا؟",
  "ar-3-dialogue-7": "لَا تَقْلَقِي. عِنْدَكِ زُكَامٌ فَقَطْ. اِشْرَبِي مَاءً كَثِيرًا.",
  "ar-3-dialogue-8": "شُكْرًا يَا دُكْتُورُ!",
  "ar-4-dhahabou": "ذَهَبُوا إِلَى السُّوقِ", "ar-4-ma-dhahabtou": "مَا ذَهَبْتُ إِلَى المَدْرَسَةِ",
  "ar-4-khaif": "أَنَا خَائِفٌ", "ar-4-soudaa": "عِنْدِي صُدَاعٌ", "ar-4-najahtou": "نَجَحْتُ فِي الِامْتِحَانِ!",
  "ar-4-recit": "أَمْسِ، ذَهَبَ خَالِدٌ مَعَ فَرِيقِهِ إِلَى المَلْعَبِ. كَانَ الجَوُّ حَارًّا جِدًّا. فِي البِدَايَةِ، كَانَ خَالِدٌ قَلِقًا لِأَنَّ الفَرِيقَ الآخَرَ كَانَ قَوِيًّا. لَعِبَ خَالِدٌ كُرَةَ القَدَمِ مَعَ أَصْدِقَائِهِ، وَرَكَضَ بِسُرْعَةٍ. فِي النِّهَايَةِ، أَخَذَ فَرِيقُهُ الكَأْسَ! فَرِحَ خَالِدٌ كَثِيرًا وَضَحِكَ مَعَ أَصْدِقَائِهِ، وَكَانَ المُدَرِّبُ فَخُورًا بِالفَرِيقِ. بَعْدَ ذَلِكَ، شَرِبَ خَالِدٌ عَصِيرَ بُرْتُقَالٍ، ثُمَّ ذَهَبَ إِلَى البَيْتِ وَنَامَ بَاكِرًا.",
  "ar-4-dialogue-1": "عَفْوًا، أَيْنَ المَتْحَفُ الوَطَنِيُّ؟",
  "ar-4-dialogue-2": "اِمْشِي، مُسْتَقِيمًا. ثُمَّ اِنْعَطِفِي، يَمِينًا، عِنْدَ إِشَارَةِ المُرُورِ.",
  "ar-4-dialogue-3": "شُكْرًا جَزِيلًا! هَلْ هُوَ بَعِيدٌ؟",
  "ar-4-dialogue-4": "لَا، إِنَّهُ قَرِيبٌ: حَوَالَيْ عَشْرِ دَقَائِقَ مَشْيًا.",
  "ar-4-dialogue-5": "هَلْ يُوجَدُ مَقْهًى قَرِيبٌ مِنَ المَتْحَفِ؟",
  "ar-4-dialogue-6": "نَعَمْ، بِجَانِبِ المَتْحَفِ مُبَاشَرَةً.",
  "ar-4-dialogue-7": "مُمْتَازٌ! شُكْرًا.",
  "ar-4-dialogue-8": "عَلَى الرَّحْبِ وَالسَّعَةِ. مَعَ السَّلَامَةِ!",
  "ar-5-malaab": "مَلْعَبٌ", "ar-5-rakib": "رَاكِبٌ", "ar-5-zurna": "زُرْنَا المَتْحَفَ",
  "ar-5-baytuhum": "هَذَا بَيْتُهُمْ", "ar-5-khali": "هَذَا خَالِي",
  "ar-5-recit": "فِي العُطْلَةِ، سَافَرَ يَاسِينُ مَعَ عَائِلَتِهِ إِلَى وَهْرَانَ. رَكِبُوا السَّفِينَةَ مِنْ مَرْسِيلِيَا، وَكَانَتِ الرِّحْلَةُ طَوِيلَةً. فِي وَهْرَانَ، سَكَنُوا فِي فُنْدُقٍ قَرِيبٍ مِنَ الكُورْنِيشِ. أَوَّلًا، سَبَحَ يَاسِينُ فِي البَحْرِ، وَكَانَ فَرِحًا جِدًّا. ثُمَّ زَارُوا المَدِينَةَ القَدِيمَةَ، وَعَبَرُوا جِسْرًا كَبِيرًا، وَرَسَمَ يَاسِينُ المَنْظَرَ الجَمِيلَ. بَعْدَ ذَلِكَ، أَكَلُوا السَّمَكَ فِي مَطْعَمٍ قَرِيبٍ مِنَ البَحْرِ. طَبَخَ الطَّبَّاخُ السَّمَكَ بِالزَّيْتِ وَالبَهَارَاتِ، وَكَانَ الأَكْلُ لَذِيذًا جِدًّا. فِي المَسَاءِ، كَتَبَ يَاسِينُ رِسَالَةً لِجَدَّتِهِ. أَخِيرًا، نَامَ فِي الفُنْدُقِ. غَدًا، سَيَرْكَبُونَ القِطَارَ إِلَى الجَزَائِرِ العَاصِمَةِ.",
  "ar-5-dialogue-1": "السَّلَامُ عَلَيْكُمْ! أُرِيدُ تَذْكِرَةً إِلَى الجَزَائِرِ العَاصِمَةِ.",
  "ar-5-dialogue-2": "وَعَلَيْكُمُ السَّلَامُ! مَتَى تُرِيدِينَ السَّفَرَ؟",
  "ar-5-dialogue-3": "غَدًا صَبَاحًا، إِنْ أَمْكَنَ.",
  "ar-5-dialogue-4": "القِطَارُ يَنْطَلِقُ السَّاعَةَ الثَّامِنَةَ.",
  "ar-5-dialogue-5": "كَمْ سَاعَةً تَسْتَغْرِقُ الرِّحْلَةُ؟",
  "ar-5-dialogue-6": "الرِّحْلَةُ تَسْتَغْرِقُ أَرْبَعَ سَاعَاتٍ.",
  "ar-5-dialogue-7": "مُمْتَازٌ! تَفَضَّلْ، وَشُكْرًا جَزِيلًا.",
  "ar-5-dialogue-8": "عَفْوًا! رِحْلَةً سَعِيدَةً!"
},
"voix_sons": {"ar-2-dialogue-2": "ar-leo", "ar-2-dialogue-4": "ar-leo", "ar-2-dialogue-6": "ar-leo", "ar-3-dialogue-1": "ar-leo", "ar-3-dialogue-3": "ar-leo", "ar-3-dialogue-5": "ar-leo", "ar-3-dialogue-7": "ar-leo", "ar-4-dialogue-2": "ar-leo", "ar-4-dialogue-4": "ar-leo", "ar-4-dialogue-6": "ar-leo", "ar-4-dialogue-8": "ar-leo", "ar-5-dialogue-2": "ar-leo", "ar-5-dialogue-4": "ar-leo", "ar-5-dialogue-6": "ar-leo", "ar-5-dialogue-8": "ar-leo"},
"images": {
  "livre": {"fr": "livre", "prompt": "a closed red school book lying flat", "personnages": []},
  "crayon": {"fr": "crayon", "prompt": "a single yellow wooden pencil with a pink eraser, drawn diagonally", "personnages": []},
  "sac": {"fr": "sac d'école", "prompt": "a blue children's school backpack", "personnages": []},
  "poisson": {"fr": "poisson", "prompt": "a small orange fish", "personnages": []},
  "chat": {"fr": "chat", "prompt": "a grey cat sitting", "personnages": []},
  "oiseau": {"fr": "oiseau", "prompt": "a small blue bird standing", "personnages": []},
  "chien": {"fr": "chien", "prompt": "a brown dog standing", "personnages": []},
  "lapin": {"fr": "lapin", "prompt": "a white rabbit sitting", "personnages": []},
  "poule": {"fr": "poule", "prompt": "a brown hen", "personnages": []},
  "pomme": {"fr": "pomme", "prompt": "a red apple", "personnages": []},
  "banane": {"fr": "banane", "prompt": "a yellow banana", "personnages": []},
  "orange": {"fr": "orange", "prompt": "a round orange citrus fruit with a single green leaf, plain fruit only, no face, no eyes, not personified", "personnages": []},
  "fraise": {"fr": "fraise", "prompt": "a red strawberry with green leaves on top, plain fruit only, no face, no eyes, no arms, no legs, not personified", "personnages": []},
  "raisin": {"fr": "raisin", "prompt": "a bunch of purple grapes", "personnages": []},
  "main": {"fr": "main", "prompt": "a child's open hand, palm facing the viewer", "personnages": []},
  "pied": {"fr": "pied", "prompt": "a child's bare foot seen from the side", "personnages": []},
  "oeil": {"fr": "œil", "prompt": "one friendly child's eye, close-up, with eyelashes", "personnages": []},
  "maison": {"fr": "maison", "prompt": "a small house with a red roof and a door, nothing else in front of the house, no animal, no person", "personnages": []},
  "soleil": {"fr": "soleil", "prompt": "a bright yellow sun with rays", "personnages": []},
  "voiture": {"fr": "voiture", "prompt": "a small red car seen from the side, empty, no driver and no passenger visible inside", "personnages": []},
  "bus": {"fr": "bus", "prompt": "a yellow public transit city bus seen from the side, low-floor design with a flat front, not an American school bus shape, empty, no driver and no passengers visible inside", "personnages": []},
  "velo": {"fr": "vélo", "prompt": "a green bicycle seen from the side", "personnages": []},
  "lait": {"fr": "verre de lait", "prompt": "a glass of white milk", "personnages": []},
  "the": {"fr": "verre de thé", "prompt": "a small glass of amber tea", "personnages": []},
  "jus-orange": {"fr": "verre de jus d'orange", "prompt": "a glass of orange juice with an orange slice on the rim", "personnages": []},
  "chat-sur-table": {"fr": "chat sur la table", "prompt": "a grey cat sitting on top of a wooden table", "personnages": []},
  "chat-sous-table": {"fr": "chat sous la table", "prompt": "a grey cat sitting on the floor under a wooden table, clearly beneath the tabletop", "personnages": []},
  "chat-cote-table": {"fr": "chat à côté de la table", "prompt": "a grey cat sitting on the floor next to a wooden table, beside it, not under it, empty table with nothing on it, no toy, no ball", "personnages": []},
  "soleil-brulant": {"fr": "soleil brûlant", "prompt": "a very hot sunny day: a huge blazing sun above a dry landscape with heat waves, empty landscape, no person, no child", "personnages": []},
  "neige": {"fr": "neige", "prompt": "a snowy winter day with falling snowflakes and a small house covered in snow", "personnages": []},
  "pluie": {"fr": "pluie", "prompt": "a rainy day with dark clouds and rain falling on a small house, empty street in front of the house, no person, no child", "personnages": []},
  "ecole": {"fr": "école", "prompt": "a school building with a flag and a clock, empty front yard, no person, no child", "personnages": []},
  "stade": {"fr": "stade", "prompt": "an empty football stadium with a green pitch and two goals, no player, no person, no ball", "personnages": []},
  "marche": {"fr": "marché", "prompt": "an outdoor market with fruit and vegetable stalls", "personnages": []},
  "fille-ecrit": {"fr": "fille qui écrit", "prompt": "the girl sitting at a desk, writing in a notebook with a pencil", "personnages": ["fille"]},
  "garcon-ecrit": {"fr": "garçon qui écrit", "prompt": "the boy sitting at a desk, writing in a notebook with a pencil", "personnages": ["garcon"]},
  "fille-lit": {"fr": "fille qui lit", "prompt": "the girl sitting and reading an open book", "personnages": ["fille"]},
  "enfants-jouent": {"fr": "enfants qui jouent ensemble", "prompt": "the boy in his green sweater and the girl in her orange tunic playing ball together, smiling, do not swap their clothes or hair", "personnages": ["garcon", "fille"]},
  "garcon-joue-seul": {"fr": "garçon qui joue seul", "prompt": "the boy playing alone with a ball", "personnages": ["garcon"]},
  "fille-livre": {"fr": "fille tenant un livre", "prompt": "the girl holding a red book against her chest, smiling", "personnages": ["fille"]},
  "garcon-mange-pomme": {"fr": "garçon qui mange une pomme", "prompt": "the boy eating a red apple", "personnages": ["garcon"]},
  "fille-chemise-rouge": {"fr": "fille en chemise rouge", "prompt": "the girl standing, full body, wearing a plain red long-sleeved shirt and dark trousers", "personnages": ["fille"]},
  "fille-chemise-bleue": {"fr": "fille en chemise bleue", "prompt": "the girl standing, full body, wearing a plain blue long-sleeved shirt and dark trousers", "personnages": ["fille"]},
  "garcon-chemise-rouge": {"fr": "garçon en chemise rouge", "prompt": "the boy standing, full body, wearing a plain red long-sleeved shirt and dark trousers", "personnages": ["garcon"]},
  "garcon-nage": {"fr": "garçon qui nage", "prompt": "the boy swimming in the sea, head above the water, wearing a long-sleeved swim top", "personnages": ["garcon"]},
  "garcon-mange-poisson": {"fr": "garçon qui mange du poisson", "prompt": "the boy sitting at a table eating grilled fish", "personnages": ["garcon"]},
  "garcon-dort": {"fr": "garçon qui dort", "prompt": "the boy sleeping flat on his back in a bed, the blanket pulled up to his neck and entirely covering his shoulders and torso, only his face is visible above the blanket, no shoulder and no part of his legs or feet visible outside the blanket", "personnages": ["garcon"]},
  "garcon-content": {"fr": "garçon content", "prompt": "head and shoulders portrait of the boy with a big happy smile, looking joyful", "personnages": ["garcon"]},
  "garcon-triste": {"fr": "garçon triste", "prompt": "head and shoulders portrait of the boy looking sad, corners of the mouth turned down, one small tear, no other emotion", "personnages": ["garcon"]},
  "garcon-colere": {"fr": "garçon en colère", "prompt": "head and shoulders portrait of the boy looking angry, frowning eyebrows, arms crossed", "personnages": ["garcon"]},
  "manteau": {"fr": "manteau", "prompt": "a warm dark blue winter coat with buttons, shown alone, no person", "personnages": []},
  "robe": {"fr": "robe", "prompt": "a long-sleeved purple girl's dress down to the ankles, shown alone, no person", "personnages": []},
  "chapeau": {"fr": "chapeau", "prompt": "a brown straw sun hat with a wide brim, shown alone, no person", "personnages": []},
  "mosquee": {"fr": "mosquée", "prompt": "a white mosque with a green dome and one minaret, empty front yard, no person", "personnages": []},
  "fille-robe-bleue": {"fr": "fille en robe bleue", "prompt": "the girl standing, full body, wearing a plain blue long-sleeved dress down to the ankles over dark trousers", "personnages": ["fille"]},
  "medecin-cabinet": {"fr": "chez le médecin", "prompt": "the girl sitting on an examination table in a doctor's office while a friendly adult male doctor in a white coat listens to her with a stethoscope", "personnages": ["fille"]},
  "fille-mal-tete": {"fr": "fille qui a mal à la tête", "prompt": "the girl holding her head with both hands, eyes half closed, clearly suffering from a headache", "personnages": ["fille"]},
  "fille-mal-ventre": {"fr": "fille qui a mal au ventre", "prompt": "the girl holding her belly with both hands, bent slightly forward, clearly suffering from a stomach ache", "personnages": ["fille"]},
  "fille-mal-pied": {"fr": "fille qui a mal au pied", "prompt": "the girl sitting on the floor holding her bare foot with both hands, clearly suffering from a sore foot", "personnages": ["fille"]},
  "fille-boit-eau": {"fr": "fille qui boit de l'eau", "prompt": "the girl drinking a glass of clear water", "personnages": ["fille"]},
  "fille-bonbons": {"fr": "fille qui mange des bonbons", "prompt": "the girl eating colorful candies from a small bowl", "personnages": ["fille"]},
  "ingenieur": {"fr": "ingénieur", "prompt": "a friendly adult man engineer wearing a yellow safety helmet and an orange safety vest, holding rolled building plans", "personnages": []},
  "medecin": {"fr": "médecin", "prompt": "a friendly adult man doctor in a white coat with a stethoscope around his neck", "personnages": []},
  "cuisinier": {"fr": "cuisinier", "prompt": "a friendly adult man cook wearing a white chef's hat and apron, holding a wooden spoon", "personnages": []},
  "enseignants": {"fr": "des enseignants", "prompt": "three friendly adult male teachers standing side by side, each holding a book, no children", "personnages": []},
  "enseignantes": {"fr": "des enseignantes", "prompt": "three friendly adult female teachers standing side by side, each holding a book, modest long-sleeved clothes, no children", "personnages": []},
  "enseignante": {"fr": "une enseignante", "prompt": "one friendly adult woman teacher about 35 years old, clearly grown-up with adult face and body proportions like the three teachers of the other picture, standing alone, holding a book, modest long-sleeved clothes and a long skirt, no children", "personnages": []},
  "musee": {"fr": "musée", "prompt": "a museum building with columns and wide steps, empty, no person", "personnages": []},
  "pharmacie": {"fr": "pharmacie", "prompt": "a small pharmacy shop front with a plain green cross sign and no letters anywhere, empty, no person", "personnages": []},
  "cafe": {"fr": "café", "prompt": "a small street café with a striped awning and two small round tables with chairs outside, empty, no person, no letters", "personnages": []},
  "garcon-inquiet": {"fr": "garçon inquiet", "prompt": "head and shoulders portrait of the boy looking worried and nervous, biting his lip, hands clasped", "personnages": ["garcon"]},
  "garcon-effraye": {"fr": "garçon effrayé", "prompt": "head and shoulders portrait of the boy looking scared, eyes wide open, hands raised near his face", "personnages": ["garcon"]},
  "garcon-fier": {"fr": "garçon fier", "prompt": "the boy standing proudly, chest out, hands on his hips, confident smile", "personnages": ["garcon"]},
  "coupe": {"fr": "coupe", "prompt": "a shiny golden trophy cup with two handles, no text", "personnages": []},
  "medaille": {"fr": "médaille", "prompt": "a golden medal on a red ribbon, no text", "personnages": []},
  "ballon": {"fr": "ballon", "prompt": "a classic black and white football (soccer ball)", "personnages": []},
  "bateau": {"fr": "bateau", "prompt": "a large white passenger ferry ship on a calm blue sea, seen from the side, no visible people, no text", "personnages": []},
  "train": {"fr": "train", "prompt": "a modern passenger train seen from the side, empty, no visible people, no text", "personnages": []},
  "avion": {"fr": "avion", "prompt": "a white passenger airplane flying in a blue sky, seen from the side, no text", "personnages": []},
  "hotel": {"fr": "hôtel", "prompt": "a white Mediterranean seaside hotel with arched balconies and palm trees in front, the blue sea behind, a doorman next to a luggage trolley with suitcases at the entrance, no letters, no sign text anywhere", "personnages": []},
  "grand-pere": {"fr": "chez son grand-père", "prompt": "the boy sitting on a sofa next to his smiling grandfather with a short white beard in the grandfather's cosy living room, a cup of tea on a small table", "personnages": ["garcon"]},
  "maman": {"fr": "une maman", "prompt": "one friendly adult North African mother about 35 years old wearing a simple hijab and modest long-sleeved clothes, standing alone and smiling, arms relaxed, no children, no kitchen", "personnages": []},
  "famille-couscous": {"fr": "famille qui mange du couscous", "prompt": "the girl with her father, her mother (no headscarf, hair tied back) and her grandparents (the grandmother wears a light headscarf) eating couscous together around a low round table in a traditional Algerian house with patterned tiles, a big round plate of couscous with vegetables in the middle", "personnages": ["fille"]},
  "casbah": {"fr": "famille dans une ruelle de la Casbah", "prompt": "the girl walking with her father and mother up a narrow white street with steps in the old Casbah of Algiers, white houses with small windows and blue wooden doors, no letters", "personnages": ["fille"]},
  "famille": {"fr": "une famille réunie", "prompt": "a smiling French-North African family standing together for a portrait: a grandfather, a grandmother wearing a hijab, a father, a mother without headscarf, an uncle and the boy, modest long-sleeved clothes", "personnages": ["garcon"]},
  "guichet-gare": {"fr": "guichet de la gare", "prompt": "a young adult woman wearing a hijab and modest long-sleeved clothes buying a ticket at the ticket window of the Oran railway station, a hall with white Moorish arches, a friendly male employee behind the glass, a train at the platform in the background, no clock, no departure board, no letters, no numbers, no signs", "personnages": []},
  "dattes": {"fr": "dattes", "prompt": "a small wooden bowl full of brown dates, a few dates next to it, no letters", "personnages": []},
  "garcon-grand-mere": {"fr": "garçon chez sa grand-mère", "prompt": "the boy hugging his smiling Moroccan grandmother who wears a light headscarf and a long traditional dress, in a Moroccan living room with low sofas and patterned cushions", "personnages": ["garcon"]},
  "garcon-football": {"fr": "garçon qui joue au football", "prompt": "the boy kicking a black and white football on a grass field, full body, joyful", "personnages": ["garcon"]},
  "paris": {"fr": "Paris (tour Eiffel)", "prompt": "the Eiffel Tower in Paris under a blue sky, trees at its base, no people, no letters", "personnages": []},
  "rue-alger": {"fr": "demander son chemin dans une rue d'Alger", "prompt": "a young adult woman without headscarf, in modest long-sleeved clothes, asking a friendly older man for directions in a street of Algiers with white buildings, arcades and blue shutters, the man points the way with his arm, no signs, no letters, no numbers", "personnages": []}
}
};
